In [1]:
import pandas as pd
import time

import numpy as np
import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, plot, iplot

In [2]:
data2015 = pd.read_csv('./datasets/world-happiness/2015.csv')
df2015 = pd.DataFrame(data2015)
df2015.head()

Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587   
1      Iceland  Western Europe               2            7.561   
2      Denmark  Western Europe               3            7.527   
3       Norway  Western Europe               4            7.522   
4       Canada   North America               5            7.427   

   Standard Error  Economy (GDP per Capita)   Family  \
0         0.03411                   1.39651  1.34951   
1         0.04884                   1.30232  1.40223   
2         0.03328                   1.32548  1.36058   
3         0.03880                   1.45900  1.33095   
4         0.03553                   1.32629  1.32261   

   Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                   0.94143  0.66557                        0.41978   
1                   0.94784  0.62877                        0.14145   
2                   0.87464  0.64938                        0.48357   
3                   0.88521  0.66973                        0.36503   
4                   0.90563  0.63297                        0.32957   

   Generosity  Dystopia Residual  
0     0.29678            2.51738  
1     0.43630            2.70201  
2     0.34139            2.49204  
3     0.34699            2.46531  
4     0.45811            2.45176

In [3]:
data2016 = pd.read_csv('./datasets/world-happiness/2016.csv')
df2016 = pd.DataFrame(data2016)
df2016.head()

Country          Region  Happiness Rank  Happiness Score  \
0      Denmark  Western Europe               1            7.526   
1  Switzerland  Western Europe               2            7.509   
2      Iceland  Western Europe               3            7.501   
3       Norway  Western Europe               4            7.498   
4      Finland  Western Europe               5            7.413   

   Lower Confidence Interval  Upper Confidence Interval  \
0                      7.460                      7.592   
1                      7.428                      7.590   
2                      7.333                      7.669   
3                      7.421                      7.575   
4                      7.351                      7.475   

   Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                   1.44178  1.16374                   0.79504  0.57941   
1                   1.52733  1.14524                   0.86303  0.58557   
2                   1.42666  1.18326                   0.86733  0.56624   
3                   1.57744  1.12690                   0.79579  0.59609   
4                   1.40598  1.13464                   0.81091  0.57104   

   Trust (Government Corruption)  Generosity  Dystopia Residual  
0                        0.44453     0.36171            2.73939  
1                        0.41203     0.28083            2.69463  
2                        0.14975     0.47678            2.83137  
3                        0.35776     0.37895            2.66465  
4                        0.41004     0.25492            2.82596

In [4]:
data2017 = pd.read_csv('./datasets/world-happiness/2017.csv')
df2017 = pd.DataFrame(data2017)
df2017.head()

Country  Happiness.Rank  Happiness.Score  Whisker.high  Whisker.low  \
0       Norway               1            7.537      7.594445     7.479556   
1      Denmark               2            7.522      7.581728     7.462272   
2      Iceland               3            7.504      7.622030     7.385970   
3  Switzerland               4            7.494      7.561772     7.426227   
4      Finland               5            7.469      7.527542     7.410458   

   Economy..GDP.per.Capita.    Family  Health..Life.Expectancy.   Freedom  \
0                  1.616463  1.533524                  0.796667  0.635423   
1                  1.482383  1.551122                  0.792566  0.626007   
2                  1.480633  1.610574                  0.833552  0.627163   
3                  1.564980  1.516912                  0.858131  0.620071   
4                  1.443572  1.540247                  0.809158  0.617951   

   Generosity  Trust..Government.Corruption.  Dystopia.Residual  
0    0.362012                       0.315964           2.277027  
1    0.355280                       0.400770           2.313707  
2    0.475540                       0.153527           2.322715  
3    0.290549                       0.367007           2.276716  
4    0.245483                       0.382612           2.430182

In [5]:
data2018 = pd.read_csv('./datasets/world-happiness/2018.csv')
df2018 = pd.DataFrame(data2018)
df2018.head()

Overall rank Country or region  Score  GDP per capita  Social support  \
0             1           Finland  7.632           1.305           1.592   
1             2            Norway  7.594           1.456           1.582   
2             3           Denmark  7.555           1.351           1.590   
3             4           Iceland  7.495           1.343           1.644   
4             5       Switzerland  7.487           1.420           1.549   

   Healthy life expectancy  Freedom to make life choices  Generosity  \
0                    0.874                         0.681       0.202   
1                    0.861                         0.686       0.286   
2                    0.868                         0.683       0.284   
3                    0.914                         0.677       0.353   
4                    0.927                         0.660       0.256   

   Perceptions of corruption  
0                      0.393  
1                      0.340  
2                      0.408  
3                      0.138  
4                      0.357

In [6]:
data2019 = pd.read_csv('./datasets/world-happiness/2019.csv')
df2019 = pd.DataFrame(data2019)
df2019.head()


Overall rank Country or region  Score  GDP per capita  Social support  \
0             1           Finland  7.769           1.340           1.587   
1             2           Denmark  7.600           1.383           1.573   
2             3            Norway  7.554           1.488           1.582   
3             4           Iceland  7.494           1.380           1.624   
4             5       Netherlands  7.488           1.396           1.522   

   Healthy life expectancy  Freedom to make life choices  Generosity  \
0                    0.986                         0.596       0.153   
1                    0.996                         0.592       0.252   
2                    1.028                         0.603       0.271   
3                    1.026                         0.591       0.354   
4                    0.999                         0.557       0.322   

   Perceptions of corruption  
0                      0.393  
1                      0.410  
2                      0.341  
3                      0.118  
4                      0.298

In [31]:
data = dict(type='choropleth'
            , locations = data2017['Country']
            , locationmode = 'country names'
            , z = data2017['Happiness.Score']
            , text = data2017['Country']
            , colorbar = {'title': 'Happiness'})

layout = dict(title = 'Happiness Index 2017'
              , geo = dict(showframe = False
                           , projection = {'type': 'mercator'}))

choromap2017 = go.Figure(data=[data], layout=layout)
choromap2017.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
print('hi')

hi


In [23]:
plot(choromap2017, filename = 'choromap2017.html', auto_open=False)

'choromap2017.html'

In [40]:
x = data2019['GDP per capita']
y = data2019['Healthy life expectancy'] * 100
z = data2019['Perceptions of corruption']

graph3d = go.Figure(data=[go.Scatter3d(
    x=x
    , y=y
    , z=z
    , mode='markers'
    , marker=dict(
        size=6
        , color=z
        , colorscale='Viridis'
        , opacity=0.8
    )
)])

graph3d.update_layout(scene=dict(
            xaxis_title="GDP Per Capita ($100,000s)"
            , yaxis_title="Healthy Life Expectancy (Years)"
            , zaxis_title="Perceptions of Corruption"
        )
    , title="GDP vs Life Expectancy vs Corruption"
    , margin=dict(l=0, r=0, b=0, t=0)
)
print('hi')

hi


In [30]:
plot(graph3d, filename = 'graph3d.html', auto_open=False)

'graph3d.html'

In [45]:
x = data2019['Freedom to make life choices']
y = data2019['Healthy life expectancy'] * 100
z = data2019['GDP per capita']

graph3d1 = go.Figure(data=[go.Scatter3d(
    x=x
    , y=y
    , z=z
    , mode='markers'
    , marker=dict(
        size=6
        , color=z
        , colorscale='Viridis'
        , opacity=0.8
    )
)])

graph3d1.update_layout(scene=dict(
            xaxis_title="Freedom to Make Life Choices"
            , yaxis_title="Healthy Life Expectancy (Years)"
            , zaxis_title="GDP Per Capita ($100,000s)"
        )
    , title="GDP vs Life Expectancy vs Corruption"
    , margin=dict(l=0, r=0, b=0, t=0)
)
print('hi')

hi


In [33]:
plot(graph3d1, filename = 'graph3d1.html', auto_open=False)

'graph3d1.html'

In [42]:
data = px.data.gapminder()
gapminder = px.scatter(
    data
    , x="gdpPercap"
    , y="lifeExp"
    , animation_frame="year"
    , animation_group="country"
    , size="pop"
    , color="continent"
    , hover_name="country"
    , log_x=True
    , size_max=55
    , range_x=[100, 100000]
    , range_y=[25, 90]
)

gapminder.update_layout(
    xaxis_title="GDP Per Capita ($)"
    , yaxis_title="Life Expectancy (Years)"
    , title="GDP VS Life Expectancy"
    , margin=dict(l=0, r=0, b=0, t=40)
)

plot(gapminder, filename = 'gapminder.html', auto_open=False)

'gapminder.html'

In [10]:
fig = go.Figure(data=go.Scatter(
    x=data2019['GDP per capita']
    , y=data2019['Score']
    , mode='markers'
    , hovertext=data2019['Country or region']
    , marker=dict(
        size=data2019['Score'] * 3
        , color=data2019['Score']
    )
))

fig.show()

In [45]:
X = data2019['GDP per capita'].values
y = data2019['Score'].values

from sklearn.linear_model import LinearRegression

X = X.reshape(-1 , 1)

model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [46]:
model.coef_

array([2.218148])

In [55]:
a = []
for i in range(200):
    a.append(model.predict([[i/100]]))

In [56]:
a

[array([3.39934518]),
 array([3.42152666]),
 array([3.44370814]),
 array([3.46588962]),
 array([3.4880711]),
 array([3.51025258]),
 array([3.53243406]),
 array([3.55461554]),
 array([3.57679702]),
 array([3.5989785]),
 array([3.62115998]),
 array([3.64334146]),
 array([3.66552294]),
 array([3.68770442]),
 array([3.7098859]),
 array([3.73206738]),
 array([3.75424886]),
 array([3.77643034]),
 array([3.79861182]),
 array([3.8207933]),
 array([3.84297478]),
 array([3.86515626]),
 array([3.88733774]),
 array([3.90951922]),
 array([3.9317007]),
 array([3.95388218]),
 array([3.97606366]),
 array([3.99824514]),
 array([4.02042662]),
 array([4.0426081]),
 array([4.06478958]),
 array([4.08697106]),
 array([4.10915254]),
 array([4.13133402]),
 array([4.1535155]),
 array([4.17569698]),
 array([4.19787846]),
 array([4.22005994]),
 array([4.24224142]),
 array([4.2644229]),
 array([4.28660438]),
 array([4.30878586]),
 array([4.33096734]),
 array([4.35314882]),
 array([4.3753303]),
 array([4.39751178]